### ISSUE TITLE
Support for TreeSummarizedExperiment?

### ISSUE THREAD

**Issue by antagomir** [david-barnett/microViz#117]
We have built framework for microbiome data science around the [TreeSummarizedExperiment](https://f1000research.com/articles/9-1246) data container (Huang et al 2021). Some examples are available in [OMA](https://microbiome.github.io/OMA) gitbook. This has taken over our earlier development work on the _microbiome_ R/Bio pkg.

Recently, we received a few requests on tools in the microViz package. This could be facilitated by adding _TreeSummarizedExperiment_ support in the microViz package.

**Comment by david-barnett** [comment]
Hi Leo,
Thanks for reaching out.

I like the general idea of using the TreeSummarizedExperiment class as a successor to phyloseq, as a data container for microbiome data. 
In the longer term, I do intend to move my development activities away from phyloseq, but I do not know yet exactly how that transition will look. I hope to find time to start experimenting with treeSE, so thanks for developing and sharing the OMA book, and mia 🙂

For now, If I understand correctly, you refer to questions from users who are primarily using treeSE and mia, but would like to use also some particular function(s) from microViz ?

In the short term, I think that a function to convert easily from treeSE to phyloseq would be a pragmatic solution. I see there is already a function `mia::makePhyloseqFromTreeSE` . Do you think this is sufficient for basic interoperability in the short term?

**Comment by antagomir** [comment]
Thanks for the prompt response. Yes, received some questions about using various microViz methods in combination with TreeSE, and wanted to highlight this. 

I agree that the current solution is to use the (already existing) conversion function `makeTreeSEFromPhyloseq()`.

Optimal TreeSE support might be a bit different than just adding TreeSE as a possible input format since the logic of system is somewhat different. Some specialized support is already available in the broader SummarizedExperiment framework for ordinations, heatmaps, and other techniques and building on that could be useful.
