### ISSUE TITLE
interactive site inactive

### ISSUE THREAD

**Issue by skose82** [david-barnett/microViz#129]
Hi there,

I'm trying out microViz but came upon a snag of the interactive page being grayed out/not functioning. I tried tax_fix() etc also but the interactive page of that is not working either. Any known issues here or something I'm missing?

Many thanks
SK

**Comment by david-barnett** [comment]
Hi SK

If I understand you correctly, running either tax_fix_interactive or ord_explore results in only a grayed out page in your web browser.

1) Are any errors appearing in your console output when you run these commands?
2) Could you post your session info /package versions?
3) what browser?

**Comment by david-barnett** [comment]
assuming this problem is resolved, feel free to reopen if not
