### ISSUE TITLE
Cannot build PCoA plot using ord_plot 

### ISSUE THREAD

**Issue by LauGuaUuu** [david-barnett/microViz#140]
Dear Davit,

Thank you for your very useful and cute package, Microviz. With my student we are having problems building PCoA plot with ord_plot function. We get the following error message:

Error in dplyr::bind_cols():
! Can't recycle ..1 (size 0) to match ..2 (size 10).
Backtrace:
 1. ... %>% ord_plot(color = "Heatwave", size = 2)
 2. microViz::ord_plot(., color = "Heatwave", size = 2)
 3. dplyr::bind_cols(siteScoresDf, meta)

Seems like an error caused in the function by dplyr not wanting to combine 2 vectors...

He uses Windows, RStudio, with R version 4.3. We uninstalled and reinstalled several times everything, and still we cannot go around. Please, can you help us resolve the issue?.

Best wishes!

LAU

**Comment by david-barnett** [comment]
hi, sorry i did not see your message until now.

If you are still having problems, could you perhaps copy-paste the code that gives you that error?

**Comment by david-barnett** [comment]
assuming this issue is resolved, feel free to open new issue if not :)
