### ISSUE TITLE
Incomplete citation of microbiome R package

### ISSUE THREAD

**Issue by marypiper** [david-barnett/microViz#27]
Minor issue: the microbiome R package has an incomplete citation in the References section of the paper.

**Comment by david-barnett** [comment]
Thanks for spotting this. 
I have tried to fill this citation out a bit in the latest manuscript version, but the suggested citation formats I could find for the microbiome package were quite minimalist.
Lahti, Leo, and Sudarshan Shetty. 2012-2019. Microbiome R Package: Tools for Microbiome Analysis in R. https://github.com/microbiome/microbiome.

**Comment by marypiper** [comment]
I think that should be fine. Thanks for following up on this.
