### ISSUE TITLE
girafe_html

### ISSUE THREAD

**Issue by atgustin** [david-barnett/microViz#28]
Hello - can't wait to get to work using this package. Thank you for offering it!  

I'm able to initiate a new browser window (in firefox or safari) but when the new window comes up, clicking the edit menu produces no options.  My meta data are available in drop down boxes, but there are no images in the view window. 

When I stop running the command in Rstudio it provides an error with traceback as follows:

Listening on http://127...
object 'girafe_html' not found

13. | execCallbacks(timeoutSecs, all, loop$id)

12. | run_now(timeoutMs/1000, all = FALSE)

11. | service(timeout)

10. | serviceApp()

9. | ..stacktracefloor..(serviceApp())

8. | withCallingHandlers(expr, error = doCaptureStack)

7. | domain$wrapSync(expr)

6. | promises::with_promise_domain(createStackTracePromiseDomain(),      expr)

5. | captureStackTraces({     while (!.globals$stopped) {         ..stacktracefloor..(serviceApp())     } ...

4. | ..stacktraceoff..(captureStackTraces({     while (!.globals$stopped) {         ..stacktracefloor..(serviceApp())     } ...

3. | runApp(x)

2. | print.shiny.appobj(x)

1. | (function (x, ...)  UseMethod("print"))(x)

Thank you for any insights you may be able to provide!

Andrew Gustin

**Comment by david-barnett** [comment]
Hi Andrew, thanks for the report. 
To help me understand what might be going on here, it would help if you can do two things:

1. create the error again and then run `devtools::session_info()` and paste the code and the output here
2. check if you are able to run (any of) the examples for ord_explore https://david-barnett.github.io/microViz/reference/ord_explore.html (e.g. the code below) or if this gives the same error
3. If it only occurs with your phyloseq, could you just `print(your_phyloseq)` and paste the output here?

```
library(microViz)
corncob::ibd_phylo %>%
   tax_fix() %>%
   ord_explore()
```

cheers, David

**Comment by david-barnett** [comment]
@atgustin I assume you resolved this problem, feel free to reopen if not :)
