### ISSUE TITLE
p values in correlation heatmaps

### ISSUE THREAD

**Issue by BrigittevdG** [david-barnett/microViz#49]
Hello David, 

I want to ask another question; how can I show the p-values of the spearman correlation in the correlation heatmap?

**Comment by david-barnett** [comment]
Hi Brigitte

Unfortunately you currently can't do this, I intend to add this feature in a future version of microViz but I would not wait for me to do so! 

In the meantime, you might try a package like corrplot.
https://taiyun.github.io/corrplot/ 

Let's keep this issue open, I'll close it when I add the feature

**Comment by BrigittevdG** [comment]
Hi David, 

Thanks for your reply. I had already tried various functions but without good results and I wanted to know if it could be done in an easy way via the correlation heatmap. Too bad that's not possible yet, but good to know that that would be included in the future! Thanks!

**Comment by tlmontgo** [comment]
Bump bump for this feature!  I love the easy feed through with phyloseq objects, especially for quick correlations with (dense) study metadata. P-values would be amazing to have all in one!!!

**Comment by emihoe** [comment]
Hi David,
Is there a way to take the MicroViz cor_heatmap output to corrplot?
I'm not very R savy and the corrplot tutorial isn't very helpful for me.
Thank you :)

**Comment by david-barnett** [comment]
for now, here is a new example of one way to obtain and plot correlations with p-values

https://david-barnett.github.io/microViz/articles/web-only/heatmaps.html#alternative-ggplot-correlation-heatmaps-with-p-values

**Comment by david-barnett** [comment]
For now, I will consider this closed with the partial workaround at:
https://david-barnett.github.io/microViz/articles/web-only/heatmaps.html#alternative-ggplot-correlation-heatmaps-with-p-values

In the future, I hope to more fully replace complex heatmap with ggplot2 heatmaps.
