### ISSUE TITLE
Support for Robust CLR and Robust Aitchison

### ISSUE THREAD

**Issue by nr0cinu** [david-barnett/microViz#56]
Hi,

it would be great to have support for robust CLR and robust Aitchison. Both are these are now implemented in vegan (https://github.com/vegandevs/vegan/pull/458).

Thanks!
Bela

**Comment by david-barnett** [comment]
#62 
Now in 0.9.3:
- `tax_transform` supports "rclr" (robust centered log ratio)
- `dist_calc` supports "robust.aitchison" distance (as rclr & euclidean distance)

and ord_explore lists these options too
