### ISSUE TITLE
Cannot install from github, gives timeout error.

### ISSUE THREAD

**Issue by jeantonalli** [david-barnett/microViz#57]
Following the installation instructions I typed the command:

`> devtools::install_github("david-barnett/microViz@0.9.2")`

Which gives the output:

```
Error: Failed to install 'unknown package' from GitHub:
  Timeout was reached: [api.github.com] Resolving timed out after 10000 milliseconds
```

I already tried with libcurl and wininet methods, but doesnt seem to work.

**Comment by david-barnett** [comment]
Slow reply from me as I was on holiday, sorry. Are you still having this problem?

**Comment by jeantonalli** [comment]
Hi. Yes, I'm still having the problem.
