### ISSUE TITLE
Installation from official source

### ISSUE THREAD

**Issue by SilasK** [david-barnett/microViz#66]
Congratulations on this cool package. The only thing I could wish for is to have it installable from an official repository. 
Is this planned?

I managed to build it but I want to make sure that others can also build it easily. 

Alternatively can I somehow the complied binary share with my collegues?

**Comment by SilasK** [comment]
Another question,

If I understand correctly the `ps_extra` object is basically a phyloseq object with some extra data, which consists mainly of the string for the methods & nromalization .. used, isn't it?

**Comment by david-barnett** [comment]
Hi Silas

Glad you're finding microViz useful :) 

I hope eventually to submit to cran, but that might still take me a while.

I've just set up an R universe profile which provides binaries installable in a very similar way to cran. Hopefully this works for you! Let me know if not?
https://david-barnett.r-universe.dev/ui#package:microViz

David

**Comment by SilasK** [comment]
I'm relatively new to R. But do you think it would be possible to ask the authors of phyloseq to allow for additional storage of list like data. In this way your package could be even beter integated with existing pipelines. Just an idea.

**Comment by david-barnett** [comment]
Probably the best idea would be to extend the phyloseq S4 class, adding additional slots. I'm unlikely to have time to implement that kind of fundamental change any time soon though unfortunately

**Comment by david-barnett** [comment]
original issue resolved for now by adding  R Universe install instructions to readme
