### ISSUE TITLE
Links broken in Readme.md on github.com only

### ISSUE THREAD

**Issue by davised** [david-barnett/microViz#87]
Just a heads-up.

The links work fine from the [github.io](https://david-barnett.github.io/microViz/) site but, e.g. this [link to the reference page](https://github.com/david-barnett/microViz/blob/main/reference/index.html) from github.com is broken.

Not sure there is an easy fix but I figured I'd mention it in case you weren't aware.

Cheers,

Ed

**Comment by david-barnett** [comment]
ack, thanks for the heads up, thought I was being smart using relative links, I'll put the absolute URLs back in
