### ISSUE TITLE
tax_select using a list for input?

### ISSUE THREAD

**Issue by carmennns2** [david-barnett/microViz#99]
Hi, 

Silly question. 

I have been manually typing the taxas I would like to subset using tax_select. 
e.g. (tax_select(physeq, tax_list = c("Eisenbergiella",  "Eubacterium_g17",  "Ruminococcus_g5", "PAC001609_g"....)) + 50 taxas 

When I try to enter the taxas into a list, and use the list as input, it does not work. 
e.g. names <- as. list(c("Eisenbergiella",  "Eubacterium_g17",  "Ruminococcus_g5", "PAC001609_g"....)
tax_select(physeq, tax_list = names). 

Is there a way I can subset large number of taxas without manually typing each?

Thanks!

**Comment by david-barnett** [comment]
Hi @carmennns2 

If you already have a **vector** of taxa names, you can leave them as a **vector**. A **list** class object will not work.

If you have a **list** of taxa names, try `unlist()`

```r
your_list = list("Eisenbergiella", "Eubacterium_g17", "Ruminococcus_g5", "PAC001609_g")
tax_select(physeq, tax_list = unlist(your_list))
```

hope this helps?
